### ISSUE TITLE
Improvement for Docs

### ISSUE THREAD

**Issue by rglover** [siteleaf/siteleaf-gem#25]
Hey guys! Was just getting setup and ran into a few snags that were confusing in the docs. The problem I ran into was that I couldn't get my local environment to work until I downloaded my site theme using `siteleaf pull theme`. Before that, the browser would either hang or not resolve (using the `siteleaf server` command and pointing to `http://localhost:9292`). 

To make things easier, it may be worth moving the part of the docs where you explain the `siteleaf pull theme` step to before you start up a server. So, something like:

1.) Install the gem.
2.) Configure your site (e.g. `siteleaf config site.com`).
3.) Make a project dir (e.g. `mkdir sitename && cd sitename`)
4.) Pull your theme.
5.) Start your server.

I'm getting the hunch that this may have only been in my own case, but worth noting. I also ran into issues with the Pow URL as well `<sitename>.dev`, where I experienced the same "hanging" issue. 

If you need more info, let me know :)

**Comment by Amay22** [comment]
Yeah it's kinda obvious ``` siteleaf server``` needs that config.ru, default.html and style.css file, which are not made locally when you run the init command I guess. Hence ```siteleaf pull theme``` is a necessary part of the procedure to work locally. After this ofcourse you can go offline and edit and run locally to edit your changes.

**Comment by sskylar** [comment]
New docs for v2 are here: http://learn.siteleaf.com
