### ISSUE TITLE
Sub-Pages for a Page No Method Error

### ISSUE THREAD

**Issue by Amay22** [siteleaf/siteleaf-gem#36]
The siteleaf-gem is wrapped around the siteleaf-api. Hence every Client.get function results in a call of the siteleaf-api. But there is no api call for returnin pages inside a page i.e. sub-pages. 

https://github.com/siteleaf/siteleaf-gem/blob/master/lib/siteleaf/page.rb#L26

Hence this part of the code doesn't really work and keeps throwing an error as undefined method 'map'.

**Comment by sskylar** [comment]
Ref https://github.com/siteleaf/siteleaf-gem/pull/29
