### ISSUE TITLE
Weird "error"=>"Not found!" showing up

### ISSUE THREAD

**Issue by jdsimcoe** [siteleaf/siteleaf-gem#47]
I'm getting this error on most pages when I click from a link in the preview page on my local setup:

```log
"error"=>"Not found!"}HTTP/1.1 200 OKContent-Type: text/html
Content-Length: 4688
Date: Tue, 25 Aug 2015 19:14:42 GMT
Connection: keep-alive

<!DOCTYPE html>
<html lang="en">
  <body>
    <header class="header">
  <nav class="nav nav-primary">
  <div class="brand">
    <a href="">
      <img src="/assets/img/circle-white.svg" alt="Circle. The Internet for Your Family.">
    </a>
  </div>
  <ul>
          <li class="active">
            <a href="/circle-go">Circle Go</a>
          </li>
          <li>
            <a href="/how-circle-works">How Circle Works</a>
          </li>
          <li >
            <a href="/mycircle">MyCircle</a>
          </li>
...
```
If I refresh the page it goes away. Very strange. Any ideas?

**Comment by jdsimcoe** [comment]
Same things happens on the homepage when I click from a link on the page. When I refresh, again, it seems to go away.

**Comment by sskylar** [comment]
@jdsimcoe are you using any Javascript or browser plugins (e.g. LiveReload) that could be altering link behavior? Try disabling and see if that makes a difference.

**Comment by jdsimcoe** [comment]
@sskylar I disabled all plugins and it's still happening... want me to bundle up the theme files and send them your way for debug?

**Comment by sskylar** [comment]
@jdsimcoe Here's a couple more things you can try:

1) To confirm its not the browser, compare in another browser (e.g. Firefox).

2) To confirm its not WEBrick, try running Thin instead:

```
$ gem install thin
$ siteleaf server
```

3) To confirm its not your code, try reverting to the default theme (https://github.com/siteleaf/siteleaf-themes/tree/master/default) or create a new test site in Siteleaf.

**Comment by jdsimcoe** [comment]
@sskylar Seems to be working there. I improved some errors in template variables. Not sure exactly what fixed it. Thanks!
