### ISSUE TITLE
2.0.0.pre Pull Time Parse TypeError

### ISSUE THREAD

**Issue by Amay22** [siteleaf/siteleaf-gem#49]
Pull Request using the `2.0.0pre` siteleaf-gem from siteleaf results in `​_parse: no implicit conversion of nil into String (TypeError)` 
This error occurs in the new date instance that has been added to every post and page and collection. `Time.parse` is a Jekyll function and it exepects the correct date format. Maybe API call to siteleaf is not returning the correct date.
Attaching link to point where I think the TypeError is occuring. `key?('date')` function only checks the existence of the date key and not that if is nil or not.

https://github.com/oakstudios/jekyll-siteleaf/blob/3e79569c2841c45ff57f3043a6c169c21b26adab/lib/jekyll/siteleaf/postable.rb#L46

https://github.com/siteleaf/siteleaf-gem/blob/2.0.0.pre/lib/siteleaf/content.rb#L28

**Comment by Amay22** [comment]
Also the test for the jekyll-sitleaf repo doesn't check for a nil instance. https://github.com/oakstudios/jekyll-siteleaf/blob/master/test/test_postable.rb#L15-L19

**Comment by sskylar** [comment]
Thanks for catching this, publish date is now optional in V2.

Fixed in 2.0.0.pre.beta5: https://rubygems.org/gems/siteleaf/versions/2.0.0.pre.beta5
