### ISSUE TITLE
Need Siteleaf Command-Line Tool to be Silent

### ISSUE THREAD

**Issue by Amay22** [siteleaf/siteleaf-gem#50]
We plan on automating the siteleaf push and pull process using jenkins. Using Capistrano as our base Rake DSL. Unfortunately it cannot answer to siteleaf y/n prompts that ask if the user wants to delete or not. If this statment could be overriden that would be awesome.

https://github.com/siteleaf/siteleaf-gem/blob/2.0.0.pre/bin/siteleaf#L250

**Comment by sskylar** [comment]
To automatically select yes (y), run your command with [yes](https://en.wikipedia.org/wiki/Yes_(Unix)):

```
$ yes | siteleaf push
```
Or for no (n), use:

```
$ yes n | siteleaf push
```

(note: if using a Gemfile, run as `bundle exec siteleaf`)
