### ISSUE TITLE
Markdown files Timestamp makes Push and Pull Mandatory.

### ISSUE THREAD

**Issue by Amay22** [siteleaf/siteleaf-gem#51]
Collection files are being re-downloaded and re-uploaded during pull and push operations respectively even  if there is no change in these collection markdowns. The only change would be the time-stamp. which changes everytime we pull. Hence, after every subsequent pull the markdowns are re-downloaded even if there was no change in them and then they are pushed back up. Whereas the theme files are only pushed or pulled when they are modified in some manner.

It would be difficult to figure out which files were modified in an automated process where we store the console output.

**Comment by sskylar** [comment]
That should only happen once. Once your dates are in sync (push then pull), they will no longer update.

If you prefer not to have publish dates at all, you can remove the date attribute from Markdown altogether (first delete old collections from Siteleaf, and then push new versions without date).

**Comment by Amay22** [comment]
@sskylar Everytime I push or pull the theme files are not pushed or pulled if they don't change but that's not the case for Collection Markdowns. The Markdowns are constant and they are still getting uploaded every single time. As far as the date attribute is concerned then there was no date attribute in the markdowns to begin with except the ones that were in the meta-field which also has not changed. 
https://github.com/NYULibraries/library.nyu.edu/tree/development/site

**Comment by sskylar** [comment]
Try this:

1. Delete all collections from Siteleaf.

2. Push site (make sure your .markdown files do not contain `date` first).

3. Pull site.

You'll get a few changes back in the last step (Siteleaf will normalize YAML formatting), but should now be in sync.
