### ISSUE TITLE
CMS Enhancement: Meta-Field Format check

### ISSUE THREAD

**Issue by Amay22** [siteleaf/siteleaf-gem#54]
The Meta-Fields in the new V2 CMS are capable of handling YAML format. As the people using the CMS may enter incorrectly formatted data. It would raise error in parsing that data. Especially if the theme code expects a certain data format from that meta-field.

**Comment by sskylar** [comment]
Will keep in mind for the CMS, but closing here as its not related to Gem.

If you wanted to fool proof your theme code, you could use Liquid to check the value first (for example if you are expecting a Hash, check for presence of key first).
