### ISSUE TITLE
GEM Enhancement Push customization

### ISSUE THREAD

**Issue by Amay22** [siteleaf/siteleaf-gem#55]
Add ability to push theme, push file, push individual folder to Siteleaf rather than have to push whole site 
`Siteleaf Push` command pushes all files to github i.e. all the theme files and the markdowns in one go.
We need the gem to have the ability to push individual files or folders. So if the change is made only to the theme or just the styling so we can just push the theme or the sass directory respectively and the markdowns won't get overwritten.

**Comment by sskylar** [comment]
Any files you don't want to sync can be added to `.siteleafignore`
