### ISSUE TITLE
Site Metadata is not being saved. v2

### ISSUE THREAD

**Issue by Amay22** [siteleaf/siteleaf-gem#57]

**Comment by sskylar** [comment]
Upgrade to the latest version (beta7) and you should be set here.

**Comment by Amay22** [comment]
@sskylar Error was in the site not in the gem. it seems to work now but I got this in red on the site on the settings page of the site.

`The operation: #1, :w=>1} @fields=nil> failed with error 12527: "not okForStorage" See https://github.com/mongodb/mongo/blob/master/docs/errors.md for details about this error.`

Also the color of the save button remains green after saving.
