### ISSUE TITLE
Input Fields in Siteleaf CMS. v2 site

### ISSUE THREAD

**Issue by Amay22** [siteleaf/siteleaf-gem#59]
When you put in code consisting input tags like select from list or text box in the body of a post or a page or a collection. The CMS picks it up and creates it's representation right below the body. Pretty cool but we loose control of the code i.e. the code in the body textarea is modified and the HTML tags for select fields in the body disappear. Moreover, the submit button appears down below and the save button disappears.

**Comment by sawyerh** [comment]
@Amay22 Good catch, pushing a fix for this now.
