### ISSUE TITLE
`siteleaf pull` should delete file locally if it no longer exists remotely

### ISSUE THREAD

**Issue by barnabyalter** [siteleaf/siteleaf-gem#60]
If a user deletes a file on the remote Siteleaf cms, performing a `siteleaf pull` locally should delete those files. This way a pull and a push will not restore any deleted files to the remote site and guarantees that there is a non-manual way to sync up local and remote repositories.

**Comment by sskylar** [comment]
Done, you should now get a prompt:

```
$ bundle exec siteleaf pull
Reading site...
=> 0 file(s) downloaded. Delete the following 1 unmatched local file(s)?
foo.md
(y/n)?
```
