### ISSUE TITLE
Server Not Starting after El Capitan Update

### ISSUE THREAD

**Issue by johnchourajr** [siteleaf/siteleaf-gem#61]
Just updated to El Capitan, and I'm trying to get my siteleaf stuff up and running. 

Got this error when running the server start command. 

```
$ siteleaf s
sh: rackup: command not found
```

**Comment by sskylar** [comment]
Sounds like El Capitan ate your [Rack](https://github.com/rack/rack) gem. 

Try:

```
gem uninstall siteleaf && gem install siteleaf
```

If that doesn't work, you can re-install rack manually:

```
gem install rack
```

If you are still having problems, I'd recommending doing a clean Ruby install using [rbenv](https://github.com/sstephenson/rbenv).

**Comment by johnchourajr** [comment]
You're a wizard sir!
