### ISSUE TITLE
Doesn't handle nil defaults

### ISSUE THREAD

**Issue by larryfox** [siteleaf/siteleaf-gem#63]
1. Create a site without the default theme
2. `siteleaf pull`
3. `undefined method 'empty?' for nil:NilClass (NoMethodError)`

https://github.com/siteleaf/siteleaf-gem/blob/c74d5ab0fffa5124ea4dc69c6575824f6a0d011e/lib/siteleaf/site.rb#L66

(I'd also be up for always including `defaults` in the API response, even if it's an empty array)

**Comment by sskylar** [comment]
Yes, I would expect API to return `defaults: []` not `defaults: nil`
