### ISSUE TITLE
Reasons for many publishing failures

### ISSUE THREAD

**Issue by barnabyalter** [siteleaf/siteleaf-gem#69]
Related to Issue #68, we have received a lot of the following errors when trying to publish from the command line:

```
Publish error: POST https://api.github.com/repos/NYULibraries/library.nyu.edu/git/trees: 405 - <html>
 <head><title>405 Not Allowed</title></head>
 <body bgcolor="white">
 <center><h1>405 Not Allowed</h1></center>
 <hr><center>nginx</center>
 </body>
 </html>
```

We've also received `End of file` errors also followed by `Publish completed.` and no error code.

In both cases the publish has not been completed.

**Comment by sskylar** [comment]
Unfortunately this error is out of scope for the Gem, moved to the appropriate (internal) channel.
